import Footer from "@/components/Footer";
import { AppContextProvider } from "./contexts/AppContext";
import "./globals.css";


export const metadata = {
  title: "Casting Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body>
         <AppContextProvider>
        {children}
        </AppContextProvider>
      </body>
      <Footer/> 
 
    </html>
  );
}
